### ISSUE TITLE
Any possibility to use mobile subscription to watch premium

### ISSUE THREAD

**Issue by Udhay707** [Vikassm73/plugin.video.botallen.hotstar#2]
Is there a way to use mobile subscription to access premium contents by changing the user agent?
 If yes please let me know where to modify, I'll use my mobile's user-agent.

**Comment by Vikassm73** [comment]
you can use mobile subscription. Before opening, Right click App. Enter "settings". Select Login Option. It will ask mobile number, OTP. After that check premium contents

**Comment by Udhay707** [comment]
Hey thanks but I'm unable to login, getting error every time when I tried to login.

**Comment by Vikassm73** [comment]
download and update again. and let me know the status

**Comment by vaibhavpathak007** [comment]
Able to login now but with mobile plan. It says 'you dont have valid subscription to watch'. I think you need to change `'X-HS-Platform': 'PCTV'` to something which is mobile specific then it should work.

**Comment by Udhay707** [comment]
Thanks for your fix 
I am able to login now, but just as mentioned in the last comment I'm not able to watch premium content.

**Comment by Vikassm73** [comment]
> Able to login now but with mobile plan. It says 'you dont have valid subscription to watch'. I think you need to change `'X-HS-Platform': 'PCTV'` to something which is mobile specific then it should work.

Done correction. Please check now

**Comment by Vikassm73** [comment]
> Thanks for your fix I am able to login now, but just as mentioned in the last comment I'm not able to watch premium content.

Please download and update addon. 

After that Enable "Debug Log". Logout and Login again and send log to
vikassm73@gmail.com

**Comment by vaibhavpathak007** [comment]
Same issue after latest update.
Sent you the kodi.log file which was generated. Hope it will help

**Comment by Vikassm73** [comment]
does your mobile subscription works in a mobile browser? Or it works only using app?

**Comment by vaibhavpathak007** [comment]
It works only on android app. On browser it asks to upgrade plan.

Thanks,
Vaibhav

**Comment by Vikassm73** [comment]
Try new update

**Comment by Udhay707** [comment]
> Try new update

Wow!! Working great 
Thanks

**Comment by vaibhavpathak007** [comment]
Excellent work 💯
Working absolutely fine 👍
