### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by MrSShiv** [Vikassm73/plugin.video.botallen.hotstar#3]
When tried to login , " Error 400: Invalid response from server " being popped up.

**Comment by twoEyedPotat** [comment]
I am also facing the same.
I followed the comment thread in your PR to botallen repo and found Manzoor saying he could login after you changed something (?).

Adding to that,
1. If I click on logout, it displays logout is successful, but the loading icon does not go away.
2. Sometimes it is throwing keyerror 'subItem' - Difficult to reproduce, encountered this once or twice and after restarting kodi, could not get this.

**Comment by Vikassm73** [comment]
Try login, Logout from outside. i.e. right click on addon, enter setting and try this option

New correction done. Logout first and login again. There after try to play.

In future, do login without logout if required. (Otherwise you will get similar error message)

**Comment by twoEyedPotat** [comment]
Working for me now ! Thanks !
