### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Daredevil1092** [Vikassm73/plugin.video.botallen.hotstar#4]
I can't log in to the addon as this error is keeps on showing.
Please help me through or update the addon as soon as possible.

![Capture](https://user-images.githubusercontent.com/112254137/201270169-d53ec2be-15b8-48e3-b1e4-2acdd62ced8f.PNG)

**Comment by Vikassm73** [comment]
just logout and login again. If  you are using it without login then just logout
